### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by sohayb** [danielemaddaluno/Android-Update-Checker#3]
Hello,
Can you add Maven support to the repo so it can be fetched through gradle online dependencies? (allows faster project update rather than pulling each fix)
Thanks

**Comment by syrakozz** [comment]
+1

**Comment by danielemaddaluno** [comment]
Hi!
So, I'm trying to publish the aar file to Maven Central with Gradle but I got an error, if you could help me I posted the question here: http://stackoverflow.com/questions/28383415/publish-an-aar-file-to-maven-central-with-gradle-not-working
Thanks in advance!

**Comment by danielemaddaluno** [comment]
Hi, I finally added the support to Maven, at the moment the lib is not on the Maven Central (but it will be soon) but you can add this repository url:  'http://dl.bintray.com/danielemaddaluno/maven/' and include it. See the [README.md](https://github.com/danielemaddaluno/Android-Update-Checker/blob/master/README.md) for more details on how to include the library automatically.

**Comment by sohayb** [comment]
That's awesome! Thanks a lot, sorry wasn't able to help because I'm pretty overloaded :)

**Comment by danielemaddaluno** [comment]
I published the library on [Maven Central](https://oss.sonatype.org/content/repositories/releases/com/github/danielemaddaluno/androidupdatechecker/library/).
See the [README.md](https://github.com/danielemaddaluno/Android-Update-Checker/blob/master/README.md) for more details on how to include the library automatically.
