### ISSUE TITLE
Orientation Change

### ISSUE THREAD

**Issue by slawekkrol** [danielemaddaluno/Android-Update-Checker#4]
Hello!

Firstly thanks for great library, I was looking for something like this to my app. 
I found one little issue. My application use only portrait orientation, but if you dialog was showed and user click "OK", orientation in my app is reset and is also landcsape.

I think you should save previous orientation in your OrientationUtils class

Regards
S. Krol

**Comment by danielemaddaluno** [comment]
I see... :S After setRequestedOrientation is applied the developer manifest defined android:screenOrientation="portrait" is completely ignored... Saving the previous orientation works fine for this but not for cases in which orientation is not set...
I'm looking forward a unique solution, maybe I will programmatically test android:screenOrientation and implement a specific solution for all the cases

**Comment by danielemaddaluno** [comment]
I think I solved this issue adding a method "getManifestOrientation" inside the OrientationUtils class. Let me know if it works fine for you. Could you manually import the library and test it for me?
If it works I'll close the issue.
Thank you!

**Comment by slawekkrol** [comment]
Manually import works, thanks. Please update maven repository

**Comment by danielemaddaluno** [comment]
Repository updated to 1.0.1. Thank you again!
