### ISSUE TITLE
Samsung Galaxy Note 4 (SM-910G) Lollipop Update????

### ISSUE THREAD

**Issue by MullyMorris1983** [danielemaddaluno/Android-Update-Checker#6]
Samsung Galaxy Note 4 (SM-910G) Lollipop Update??
Could anyone who has the ability to provide a copy of the online link to the update to lollipop I will be in your debt to the death..

**Comment by danielemaddaluno** [comment]
You should read the description first. This app is a demo app for developers and programmers, it simply shows if the app (in your case Android Update Checker itself) is updated. If you have the 1.0.7 it warns you that "your app is already updated". Best Regards
